### ISSUE TITLE
Implement Topology.Orientation and Reverse() for Faces and Edges

### ISSUE THREAD

**Issue by nickger** [wassimj/Topologic#50] opened 2023-12-03 10:44 UTC
Please implement property Orientation and method Reverse() for faces and edges. It is important to check meshes and work with neighbor (but not adjacent) topologies.
(also in python would be nice).

**Comment by wassimj** [comment] 2023-12-03 12:40
Have you tried these or do you need something else?:
Face.Normal(face): [link](https://topologic.app/topologicpy_doc/topologic_pdoc/Face.html#Face.Face.Normal)
Face.Invert(face): [link](https://topologic.app/topologicpy_doc/topologic_pdoc/Face.html#Face.Face.Invert)
Edge.Direction(edge): [link](https://topologic.app/topologicpy_doc/topologic_pdoc/Edge.html#Edge.Edge.Direction)
Edge.Reverse(edge): [link](https://topologic.app/topologicpy_doc/topologic_pdoc/Edge.html#Edge.Edge.Reverse)

**Comment by wassimj** [comment] 2023-12-04 10:08
You are in the wrong repo! This is an old repository. Go to github.com/wassimj and find the projects there. Topologic is the C++ core and topologicpy is the cleaned up python API to Topologic. I will look at the issue of open shell faces having different normals. For a Cell, they are consistently pointing outwards. In an open shell, "out" is meaningless so there is no assumption about the faces.
Regarding naming: This is historical how it was named. Faces are inverted, but edges are reversed. This is proper English use. A direction is not inverted, you reverse a direction, but a face or surface is inverted (turned upside down). My philosophy with topologicpy is to add synonym methods. These are just pointers to other methods, but called differently to match people's expectations (e.g. Cell.Box is same as Cell.Prism). I will see what OCCT calls things and use the same nomenclature as a synonym.

**Comment by wassimj** [comment] 2024-04-30 04:51
I am closing this issue as there has not been any response in a long time. If the issue is not resolved, please feel free to re-open it.

**Closed by wassimj** 2024-04-30 04:51 UTC
